// Generated by CoffeeScript 1.7.1
define(['jquery', 'flight/lib/component'], function($, defineComponent) {
  return defineComponent(function() {
    this.defaultAttrs({
      gallerySelector: ".scrollableArea",
      leftHotspotSelector: ".scrollingHotSpotLeft",
      rightHotspotSelector: ".scrollingHotSpotRight",
      imageCounterSelector: ".scroll_image_counter",
      processing: false,
      currentImage: 1
    });
    this.current = function(image) {
      if (image == null) {
        image = this.attr.currentImage;
      }
      if (this.total() === 0) {
        this.attr.currentImage = 0;
      }
      return this.attr.currentImage = image;
    };
    this.total = function() {
      return this.data['photo_urls'].length;
    };
    this.setupGallery = function() {
      var $gallery;
      $gallery = this.select('gallerySelector');
      $gallery.width(this.galleryWidth);
      $(this.paths.slice(0, 5)).each((function(_this) {
        return function(index, path) {
          var html;
          html = "<a href='" + _this.href + "'>";
          html += "<img src='http://image.apartmentguide.com" + path + "' ";
          html += "width='" + _this.imageWidth + "px' height='105px'></a>";
          return $gallery.append(html);
        };
      })(this));
      return $gallery.find("img:first").addClass('current');
    };
    this.imageCount = function() {
      return "" + (this.current()) + "/" + (this.total());
    };
    this.next = function() {
      var image;
      image = this.current();
      if (image !== this.total()) {
        this.current(image += 1);
        this.updateCounter(image);
        return this.browse('right');
      }
    };
    this.previous = function() {
      var image;
      image = this.current();
      if (image !== 1) {
        this.current(image -= 1);
        this.updateCounter(image);
        return this.browse('left');
      }
    };
    this.updateCounter = function(num) {
      this.select('gallerySelector').find('img.current').removeClass('current');
      this.select('gallerySelector').find("a:nth-child(" + num + ") img").addClass('current');
      return this.select('imageCounterSelector').html(this.imageCount());
    };
    this.browse = function(direction) {
      var options;
      if (!this.processing) {
        this.processing = true;
        options = (function() {
          switch (direction) {
            case 'left':
              return {
                right: "-=" + this.imageWidth + "px"
              };
            default:
              return {
                right: "+=" + this.imageWidth + "px"
              };
          }
        }).call(this);
        return this.select('gallerySelector').animate(options, 400, (function(_this) {
          return function() {
            return _this.processing = false;
          };
        })(this));
      }
    };
    return this.after('initialize', function() {
      this.data = this.$node.data('photoplus');
      this.paths = this.data['photo_urls'] || [];
      this.href = this.$node.find('a').attr('href');
      this.imageWidth = this.$node.width();
      this.galleryWidth = this.imageWidth * this.total();
      this.photoplusId = this.$node.attr('id');
      this.resultId = this.$node.closest('.result').attr('id');
      this.select('imageCounterSelector').html(this.imageCount());
      this.$node.closest('.result').on('mouseenter', (function(_this) {
        return function() {
          return _this.setupGallery();
        };
      })(this));
      return this.on('click', {
        rightHotspotSelector: this.next,
        leftHotspotSelector: this.previous
      });
    });
  });
});
