// Generated by CoffeeScript 1.7.1
describe("photoplus", ['jquery', 'jasmine', 'jasmine-jquery', 'photoplus'], function($) {
  beforeEach(function() {
    return loadFixtures("../../../fixtures/photoplus.html");
  });
  return describe("initialize", function() {
    return it("should define the function", function() {
      return expect($().photoplus).toBeDefined();
    });
  });
});
